title: KF22 Studio
description: Apps made with 💙 in the heart of Berlin

theme: jekyll-theme-minimal
show_downloads: false
#logo: /assets/img/berlin-outline.svg

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
