title: KF22 Studio
description: Apps made with 💙 in the heart of Berlin

theme: jekyll-theme-minimal
show_downloads: false
show_github_link: false

footer:
  navigation:
    - title: Contact
      url: mailto:hello@kf22.studio
    - title: Legal Notice
      url: /legal-notice/

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
